login_view/accounts/urls.py
from django.urls import path
from .views import (
    RegisterUserView,HomeView,UserLoginView,UserLogoutView
)

app_name = "accounts"

urlpatterns =[
    path('home/',HomeView.as_view(),name='home'),
    path('regist/',RegisterUserView.as_view(),name='regist'),
    path('user_login/',UserLoginView.as_view(),name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),

]

login_view/login_view/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls'))
]

login_view/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager,AbstractBaseUser,PermissionsMixin
)
from django.urls import reverse_lazy
# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self,username,email,password=None):
        if not email:
            raise ValueError('Enter Email')
        user = self.model(
            username=username,
            email =email,
        )
        user.set_password(password)
        user.save(using=self.db)
        return user

class Users(AbstractBaseUser,PermissionsMixin):
    username=models.CharField(max_length=150)
    email=models.EmailField(max_length=255,unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    object = UserManager()

    def get_absolute_url(self):
        return reverse_lazy("accounts:home")
    

login_view/accounts/forms.py
from django import forms
from .models import Users
from django.contrib.auth.password_validation import validate_password

class RegistForm(forms.ModelForm):
    username=forms.CharField(label='名前')
    age = forms.IntegerField(label='年齢',min_value=0)
    email = forms.EmailField(label="メールアドレス")
    password= forms.CharField(label="パスワード",widget=forms.PasswordInput)

    class Meta:
        model = Users
        fields = ['username','age','email','password']

    def save(self,commit=False):
        user=super().save(commit=False)
        validate_password(self.cleaned_data['password'],user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

class UserLoginForm(forms.Form):
    email = forms.EmailField(label="メールアドレス")
    password = forms.CharField(label="パスワード",widget=forms.PasswordInput)

login_view/accounts/views.py
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView,FormView
from django.views.generic.base import TemplateView,View
from .forms import RegistForm,UserLoginForm
from django.contrib.auth import authenticate,login,logout
# Create your views here.
class HomeView(TemplateView):
    template_name = 'home.html'

class RegisterUserView(CreateView):
    template_name= 'regist.html'
    form_class = RegistForm


class UserLoginView(FormView):
    template_name = 'user_login.html'
    form_class = UserLoginForm

    def post(self,request,*args, **kwargs):
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email,password=password)
        if user is not None and user.is_active:
            login(request,user)
        return redirect('accounts:home')

class UserLogoutView(View):
    
    def get(self,request,*args, **kwargs):
        logout(request)
        return redirect('accounts:user_login')

login_view/templates/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navber-expand-lg navbar-light bg-light">
            <a class="nav-brand" href="{% url 'accounts:home' %}">ホーム</a>
            {% if user.is_authenticated %}
            <a class="nav-brand" href="{% url 'accounts:user_logout' %}">ログアウト</a>
            {% else %}
            <a class="nav-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
            <a class="nav-brand" href="{% url 'accounts:regist' %}">ユーザー登録</a>
            {% endif %}

        </nav>
            {% block content %}{% endblock %}

    </body>
</html>

login_view/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>ホーム画面です</h1>
{% endblock %}

login_view/templates/regist.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="ユーザー登録">
</form>
{% endblock %}

login_view/templates/user_login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="ログイン">
</form>
{% endblock %}